[theme]
base = "light"
primaryColor = "#3EA258"
backgroundColor = "#F8FAFB"
secondaryBackgroundColor = "#EDF3F5"
textColor = "#1D242E"
font = "sans serif"

[server]
headless = true
enableCORS = true
enableXsrfProtection = true
runOnSave = true

[browser]
gatherUsageStats = false
